# Generated by Django 5.2.7 on 2025-11-26 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("time_start", models.DateTimeField(blank=True, null=True)),
                ("time_end", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="MicroService",
        ),
        migrations.RemoveField(
            model_name="event",
            name="allowed",
        ),
        migrations.RemoveField(
            model_name="event",
            name="scans",
        ),
        migrations.RemoveField(
            model_name="scaninstance",
            name="event",
        ),
        migrations.RemoveField(
            model_name="scaninstance",
            name="student",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="gradYear",
            new_name="grad_year",
        ),
        migrations.DeleteModel(
            name="Device",
        ),
        migrations.DeleteModel(
            name="MicroService",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="ScanInstance",
        ),
    ]
